name: Run Azure Login with OpenID Connect and PowerShell

on: workflow_dispatch
      
jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 'Push image'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.STAPACR_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    